"""
StockM v1.0 - Phase 8, Lesson 2
Trade & Signal Vocabulary (data layer)
=====================================

The shared nouns of the backtesting system. Every other module - strategy,
portfolio, risk, metrics, reporting - speaks this vocabulary, so it lives in
one dependency-free module at the bottom of the dependency graph.

Single Responsibility: represent trade *intentions* and *executions* as plain,
immutable data. NO behaviour, NO pandas, NO numpy - just typed records. This
keeps the vocabulary stable: changing a strategy must never touch a Trade, and
changing a metric must never touch a Signal.

Why immutable (frozen) records
-------------------------------
A Signal is an intention at a moment in time; a Trade is a fact that happened.
Neither should be mutated after creation - mutating a closed trade would
silently rewrite history and corrupt every downstream metric. ``frozen=True``
turns that into a hard error instead of a silent bug.

Contents
--------
    TradeAction - enum: BUY / SELL / HOLD (str-mixin for clean serialisation)
    Signal      - an INTENDED action (strategy output; may be vetoed/reshaped)
    Trade       - an EXECUTED transaction (portfolio output; has a price + cost)

Timing convention (enforced by the engine, not here)
----------------------------------------------------
A Signal dated t is produced from information known up to and including t. The
trade it triggers executes at t's price (or t+1 open - configurable), never
using information after t. This module holds the records; the engine owns the
"never use the future" discipline. The canonical execution price series is
Adj Close (see the canonical-price-convention memory).
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from enum import Enum


class TradeAction(str, Enum):
    """A discrete trading action.

    ``str`` mixin so ``action.value`` serialises cleanly to JSON/YAML in the
    report (Lesson 12) and trade log (Lesson 13) without custom encoders, and
    so ``action == "BUY"`` comparisons read naturally in strategy code.
    """

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass(frozen=True)
class Signal:
    """An intended trading action at a point in time.

    Produced by a Strategy (Lesson 4) from a model prediction. A Signal is an
    *intention* - the RiskManager (Lesson 7) may reshape or veto it, and the
    Portfolio (Lesson 5) may reject it (e.g. SELL with no position). Only when
    filled does it become a Trade.

    Attributes:
        date:             The trading date the signal applies to.
        symbol:           Ticker, e.g. "RELIANCE.NS".
        action:           BUY / SELL / HOLD.
        predicted_return: The raw model output that produced the signal (audit
                          trail back to the prediction layer).
        confidence:       Optional model confidence / UP-probability in [0, 1].
        strength:         How strongly the strategy wants this, in [0, 1].
                          Reserved for position sizing (Lesson 5).
        reason:           Human-readable provenance: which rule / strategy fired.
    """

    date: date
    symbol: str
    action: TradeAction
    predicted_return: float = 0.0
    confidence: float | None = None
    strength: float = 1.0
    reason: str = ""


@dataclass(frozen=True)
class Trade:
    """An executed transaction (a fact that happened).

    Produced by the Portfolio when a Signal is filled. Immutable: once a trade
    is booked it is history and must not change - realised P&L and every metric
    derive from this record.

    Attributes:
        date:     Date of execution.
        symbol:   Ticker.
        action:   BUY / SELL (HOLD never produces a Trade).
        quantity: Shares transacted (>= 0; the sign is carried by ``action``).
        price:    Execution price (Adj Close by convention).
        value:    quantity * price (pre-cost notional).
        cost:     Transaction cost incurred this trade (commission + slippage).
        signal:   The Signal that triggered this trade (audit trail back to the
                  model prediction that caused it). None for forced exits
                  generated by the risk manager without a model signal.
    """

    date: date
    symbol: str
    action: TradeAction
    quantity: float
    price: float
    value: float
    cost: float = 0.0
    signal: Signal | None = None
